module tb_datapath;

    // ============================================================
    // CLOCK AND RESET
    // ============================================================

    logic clk;
    logic reset;


    // ============================================================
    // CONTROL SIGNALS
    // ============================================================

    logic ir_write;
    logic pc_write;

    logic a_write;
    logic b_write;

    logic aluout_write;
    logic mdr_write;

    logic reg_write;

    logic alu_src_a;
    logic [1:0] alu_src_b;

    logic [3:0] alu_op;

    logic [1:0] wb_sel;

    // 0 = PC
    // 1 = ALUOut
    logic mem_addr_sel;


    // ============================================================
    // MEMORY INTERFACE
    // ============================================================

    logic [31:0] mem_rdata;

    logic [31:0] mem_addr;
    logic [31:0] mem_wdata;


    // ============================================================
    // DECODER OUTPUTS
    // ============================================================
    //
    // These signals are generated by the decoder inside the
    // datapath and are sent to the FSM in the integrated CPU.
    //
    // They were missing from the previous datapath TB.
    // ============================================================

    logic is_rtype;
    logic is_itype;
    logic is_load;
    logic is_store;
    logic is_branch;
    logic is_jal;
    logic is_jalr;
    logic is_lui;
    logic is_auipc;

    logic [3:0] decoder_alu_op;


    // ============================================================
    // DEBUG SIGNALS
    // ============================================================

    logic [31:0] instruction;
    logic [31:0] pc_out;
    logic [31:0] aluout_out;

    logic [31:0] a_out;
    logic [31:0] b_out;

    logic [31:0] immediate_out;
    logic [31:0] alu_result_out;

    logic alu_zero;


    // ============================================================
    // ALU DEFINITIONS
    // ============================================================

    localparam ALU_ADD = 4'b0000;
    localparam ALU_SUB = 4'b0001;


    // ============================================================
    // DUT
    // ============================================================

    datapath dut (

        // --------------------------------------------------------
        // Clock and reset
        // --------------------------------------------------------

        .clk(clk),
        .reset(reset),


        // --------------------------------------------------------
        // FSM control signals
        // --------------------------------------------------------

        .ir_write(ir_write),
        .pc_write(pc_write),

        .a_write(a_write),
        .b_write(b_write),

        .aluout_write(aluout_write),
        .mdr_write(mdr_write),

        .reg_write(reg_write),


        // --------------------------------------------------------
        // ALU control
        // --------------------------------------------------------

        .alu_src_a(alu_src_a),
        .alu_src_b(alu_src_b),

        .alu_op(alu_op),


        // --------------------------------------------------------
        // Memory address control
        // --------------------------------------------------------

        .mem_addr_sel(mem_addr_sel),


        // --------------------------------------------------------
        // Writeback control
        // --------------------------------------------------------

        .wb_sel(wb_sel),


        // --------------------------------------------------------
        // Memory interface
        // --------------------------------------------------------

        .mem_rdata(mem_rdata),

        .mem_addr(mem_addr),
        .mem_wdata(mem_wdata),


        // --------------------------------------------------------
        // Decoder outputs
        // --------------------------------------------------------

        .is_rtype(is_rtype),
        .is_itype(is_itype),
        .is_load(is_load),
        .is_store(is_store),
        .is_branch(is_branch),
        .is_jal(is_jal),
        .is_jalr(is_jalr),
        .is_lui(is_lui),
        .is_auipc(is_auipc),

        .decoder_alu_op(decoder_alu_op),


        // --------------------------------------------------------
        // Debug outputs
        // --------------------------------------------------------

        .instruction(instruction),
        .pc_out(pc_out),
        .aluout_out(aluout_out),

        .a_out(a_out),
        .b_out(b_out),

        .immediate_out(immediate_out),
        .alu_result_out(alu_result_out),

        .alu_zero(alu_zero)

    );


    // ============================================================
    // CLOCK
    // ============================================================

    initial begin

        clk = 1'b0;

        forever #5 clk = ~clk;

    end


    // ============================================================
    // RESET TASK
    // ============================================================

    task reset_cpu;

        begin

            reset = 1'b1;

            ir_write     = 1'b0;
            pc_write     = 1'b0;

            a_write      = 1'b0;
            b_write      = 1'b0;

            aluout_write = 1'b0;
            mdr_write    = 1'b0;

            reg_write    = 1'b0;

            alu_src_a = 1'b0;
            alu_src_b = 2'b00;

            alu_op = ALU_ADD;

            wb_sel = 2'b00;

            // Default to instruction-fetch address.
            mem_addr_sel = 1'b0;

            mem_rdata = 32'd0;


            @(posedge clk);
            @(posedge clk);

            @(negedge clk);

            reset = 1'b0;

        end

    endtask


    // ============================================================
    // FETCH TASK
    // ============================================================

    task fetch_instruction(input logic [31:0] instruction_data);

        begin

            // Instruction is present on memory read-data bus.
            mem_rdata = instruction_data;

            // FETCH uses PC as memory address.
            mem_addr_sel = 1'b0;


            // Change write enable while clock is LOW.
            @(negedge clk);

            ir_write = 1'b1;


            // IR captures instruction.
            @(posedge clk);

            #1;


            // Disable IR write.
            @(negedge clk);

            ir_write = 1'b0;

        end

    endtask


    // ============================================================
    // MAIN TEST
    // ============================================================

    initial begin

        // ========================================================
        // RESET
        // ========================================================

        reset_cpu();


        // ========================================================
        // REGISTER PRELOAD
        // ========================================================

        // x6 = 20
        // x7 = 7
        // x10 = 100

        dut.regfile_inst.regs[6]  = 32'd20;
        dut.regfile_inst.regs[7]  = 32'd7;
        dut.regfile_inst.regs[10] = 32'd100;


        assert(dut.regfile_inst.regs[6] == 32'd20)
            else $fatal(1, "PRELOAD FAILED: x6");

        assert(dut.regfile_inst.regs[7] == 32'd7)
            else $fatal(1, "PRELOAD FAILED: x7");

        assert(dut.regfile_inst.regs[10] == 32'd100)
            else $fatal(1, "PRELOAD FAILED: x10");


        $display("Register preload verified");


        // ========================================================
        // TEST 1
        //
        // ADDI x5,x6,10
        //
        // 20 + 10 = 30
        // ========================================================

        $display("");
        $display("TEST 1: ADDI x5,x6,10");


        // FETCH

        fetch_instruction(32'h00A30293);


        // Capture x6 into A

        @(negedge clk);

        a_write = 1'b1;

        @(posedge clk);

        #1;

        @(negedge clk);

        a_write = 1'b0;


        assert(a_out == 32'd20)
            else $fatal(
                1,
                "ADDI FAILED: A expected 20, got %d",
                a_out
            );


        // Execute

        @(negedge clk);

        alu_src_a = 1'b0;
        alu_src_b = 2'b01;
        alu_op    = ALU_ADD;

        aluout_write = 1'b1;

        @(posedge clk);

        #1;

        @(negedge clk);

        aluout_write = 1'b0;


        assert(aluout_out == 32'd30)
            else $fatal(
                1,
                "ADDI FAILED: ALUOut expected 30, got %d",
                aluout_out
            );


        // Writeback

        @(negedge clk);

        wb_sel = 2'b00;
        reg_write = 1'b1;

        @(posedge clk);

        #1;

        @(negedge clk);

        reg_write = 1'b0;


        assert(dut.regfile_inst.regs[5] == 32'd30)
            else $fatal(
                1,
                "ADDI FAILED: x5 expected 30, got %d",
                dut.regfile_inst.regs[5]
            );


        $display("ADDI PASSED");


        // ========================================================
        // TEST 2
        //
        // ADD x8,x6,x7
        //
        // 20 + 7 = 27
        // ========================================================

        $display("");
        $display("TEST 2: ADD x8,x6,x7");


        fetch_instruction(32'h00730433);


        // Capture x6 and x7

        @(negedge clk);

        a_write = 1'b1;
        b_write = 1'b1;

        @(posedge clk);

        #1;

        @(negedge clk);

        a_write = 1'b0;
        b_write = 1'b0;


        assert(a_out == 32'd20)
            else $fatal(
                1,
                "ADD FAILED: A expected 20, got %d",
                a_out
            );

        assert(b_out == 32'd7)
            else $fatal(
                1,
                "ADD FAILED: B expected 7, got %d",
                b_out
            );


        // Execute A + B

        @(negedge clk);

        alu_src_a = 1'b0;
        alu_src_b = 2'b00;
        alu_op    = ALU_ADD;

        aluout_write = 1'b1;

        @(posedge clk);

        #1;

        @(negedge clk);

        aluout_write = 1'b0;


        assert(aluout_out == 32'd27)
            else $fatal(
                1,
                "ADD FAILED: ALUOut expected 27, got %d",
                aluout_out
            );


        // Write x8

        @(negedge clk);

        wb_sel = 2'b00;
        reg_write = 1'b1;

        @(posedge clk);

        #1;

        @(negedge clk);

        reg_write = 1'b0;


        assert(dut.regfile_inst.regs[8] == 32'd27)
            else $fatal(
                1,
                "ADD FAILED: x8 expected 27, got %d",
                dut.regfile_inst.regs[8]
            );


        $display("R-TYPE ADD PASSED");


        // ========================================================
        // TEST 3
        //
        // LW x5,8(x10)
        //
        // x10 = 100
        // offset = 8
        //
        // address = 108
        // ========================================================

        $display("");
        $display("TEST 3: LW x5,8(x10)");


        fetch_instruction(32'h00852283);


        // Capture x10 into A

        @(negedge clk);

        a_write = 1'b1;

        @(posedge clk);

        #1;

        @(negedge clk);

        a_write = 1'b0;


        assert(a_out == 32'd100)
            else $fatal(
                1,
                "LW FAILED: A expected 100, got %d",
                a_out
            );


        // Calculate address = 100 + 8

        @(negedge clk);

        alu_src_a = 1'b0;
        alu_src_b = 2'b01;
        alu_op    = ALU_ADD;

        aluout_write = 1'b1;

        @(posedge clk);

        #1;

        @(negedge clk);

        aluout_write = 1'b0;


        // --------------------------------------------------------
        // Verify ALU result FIRST
        // --------------------------------------------------------

        assert(aluout_out == 32'd108)
            else $fatal(
                1,
                "LW FAILED: ALUOut expected 108, got %d",
                aluout_out
            );


        // --------------------------------------------------------
        // Select ALUOut as memory address
        // --------------------------------------------------------

        mem_addr_sel = 1'b1;

        #1;


        // Debug information

        $display(
            "LW DEBUG: PC=%d ALUOut=%d mem_addr_sel=%b mem_addr=%d",
            pc_out,
            aluout_out,
            mem_addr_sel,
            mem_addr
        );


        // --------------------------------------------------------
        // Verify memory address
        // --------------------------------------------------------

        assert(mem_addr == 32'd108)
            else $fatal(
                1,
                "LW FAILED: mem_addr expected 108, got %d",
                mem_addr
            );


        // --------------------------------------------------------
        // Simulate memory response
        // --------------------------------------------------------

        @(negedge clk);

        mem_rdata = 32'hDEADBEEF;

        mdr_write = 1'b1;

        @(posedge clk);

        #1;

        @(negedge clk);

        mdr_write = 1'b0;


        // --------------------------------------------------------
        // Write MDR into x5
        // --------------------------------------------------------

        wb_sel = 2'b01;
        reg_write = 1'b1;

        @(posedge clk);

        #1;

        @(negedge clk);

        reg_write = 1'b0;


        assert(dut.regfile_inst.regs[5] == 32'hDEADBEEF)
            else $fatal(
                1,
                "LW FAILED: x5 expected DEADBEEF, got %h",
                dut.regfile_inst.regs[5]
            );


        $display("LW PASSED");


        // ========================================================
        // TEST 4
        //
        // SW x5,12(x10)
        //
        // x10 = 100
        // x5  = DEADBEEF
        //
        // address = 112
        // ========================================================

        $display("");
        $display("TEST 4: SW x5,12(x10)");


        fetch_instruction(32'h00552623);


        // Capture x10 and x5

        @(negedge clk);

        a_write = 1'b1;
        b_write = 1'b1;

        @(posedge clk);

        #1;

        @(negedge clk);

        a_write = 1'b0;
        b_write = 1'b0;


        assert(a_out == 32'd100)
            else $fatal(
                1,
                "SW FAILED: A expected 100, got %d",
                a_out
            );

        assert(b_out == 32'hDEADBEEF)
            else $fatal(
                1,
                "SW FAILED: B expected DEADBEEF, got %h",
                b_out
            );


        // Calculate address = 100 + 12

        @(negedge clk);

        alu_src_a = 1'b0;
        alu_src_b = 2'b01;
        alu_op    = ALU_ADD;

        aluout_write = 1'b1;

        @(posedge clk);

        #1;

        @(negedge clk);

        aluout_write = 1'b0;


        // Select ALUOut as memory address

        mem_addr_sel = 1'b1;

        #1;


        $display(
            "SW DEBUG: PC=%d ALUOut=%d mem_addr_sel=%b mem_addr=%d",
            pc_out,
            aluout_out,
            mem_addr_sel,
            mem_addr
        );


        assert(mem_addr == 32'd112)
            else $fatal(
                1,
                "SW FAILED: mem_addr expected 112, got %d",
                mem_addr
            );


        assert(mem_wdata == 32'hDEADBEEF)
            else $fatal(
                1,
                "SW FAILED: mem_wdata expected DEADBEEF, got %h",
                mem_wdata
            );


        $display("SW PASSED");


        // ========================================================
        // FINAL RESULT
        // ========================================================

        $display("");
        $display("======================================");
        $display("ALL DATAPATH TESTS PASSED");
        $display("======================================");

        $finish;

    end

endmodule
